### ISSUE TITLE
Passenger Support?

### ISSUE THREAD

**Issue by supairish** [firehoseio/firehose#50]
Hello!
I see in the docs that Thin and Rainbows is supported.  I was wondering if anyone has had success with using Passenger?  It would seem they support websockets as per (https://github.com/phusion/passenger-ruby-websocket-demo)  but figured I'd ask if anyone here has tried before I go down a possibly futile rabbit hole :-)

Cheers

**Comment by thoughtless** [comment]
The main question is if they support `EventMachine`. I haven't run `EventMachine` with Passenger, so I couldn't say.

**Comment by bradgessler** [comment]
Firehose is just a Rack app: https://github.com/firehoseio/firehose/blob/message-buffer/lib/firehose/rack/app.rb. We haven't tested EM yet on Phusion, but if you want to give it a try just run the following in your config.ru:

```ruby
require "firehose"
run Firehose::Rack::App.new
```

(From https://github.com/firehoseio/firehose/blob/message-buffer/lib/firehose/rack/app.rb)

I'm going to close this issue since we don't have plans to support Phusion, but I do welcome community contributions to documentation either in the form of comments to this issue or PR to our README.
